### ISSUE TITLE
[BUG] error Couldn't find package "@npmcli/query" on the "npm" registry.

### ISSUE THREAD

**Issue by BWrong** [npm/query#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

“error Couldn't find package "@npmcli/query" on the "npm" registry.“ is reported when running “yarn”

### Expected Behavior

No error

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run 'yarn'
4. See error...
Couldn't find package "@npmcli/query

### Environment

- npm: 8.15.1
- Node:16.16.0
- OS:MacOS12.5
- platform:intel
![WX20220804-103641](https://user-images.githubusercontent.com/20485299/182750936-04d13692-5f59-45e8-a9d9-1b2aa37fb765.png)

**Comment by nlf** [comment]
```
> npm show @npmcli/query time
{
  created: '2022-06-08T17:07:15.149Z',
  '1.0.0': '2022-06-08T17:07:15.375Z',
  modified: '2022-08-03T01:27:03.061Z',
  '1.0.1': '2022-06-08T17:14:27.670Z',
  '1.0.2': '2022-06-27T14:16:25.964Z',
  '1.1.0': '2022-06-28T17:04:26.449Z',
  '1.1.1': '2022-08-03T01:27:02.965Z'
}
```

it definitely is in the registry, this could be a network problem on your end or possibly something going on with yarn
